### PR TITLE
Update fanyi-baidu.ts

### LINKED ISSUE #42: [BUG] Issue with Fanyi Baidu
# User report
**Description:** ADD A SHORT DESCRIPTION HERE 

---
# Debugger data (do not alter)
**plugin_version**: "1.4.4"
**platform**: "Desktop"
**framework_version**: "1.1.9"
**obsidian_version**: "1.1.16"

### PR DESCRIPTION
**Pull request by solitary-sails**
## Type of change

- [x] Bug fix
- [ ] New localization
- [ ] New feature
- [ ] New translation service

## Description
Fix #42

### CODE REVIEW

**Comment by solitary-sails** [comment]
As we have talked in #42 ，I don't have the access to language detection API,so I don't know if it's working.
***
Other features works well, except for one thing, I found that there are still languages that cannot be translated, such as Albanian.  However, I can't get a normal response even when I directly access the API with a browser, so I suspect it's Baidu's problem.I'm trying to get in touch with their customer service, but haven't gotten a response yet.

**Comment by Fevol** [comment]
I'll assume that the Language Detection works for now. And besides, I don't think many people use need to be able to detect languages that often.

Want me to merge this as-is, or do you want to wait for confirmation from the customer service? It would be a bit strange that some languages don't translate.

**Comment by solitary-sails** [comment]
Just wait for the reply from the customer service, it shouldn't take too long.

**Comment by solitary-sails** [comment]
I got a reply. Baidu divides the service into several levels. Only the premium level can unlock the translation rights of all supported languages, the beginner level and advanced level (which I am using) can only translate the languages ​​in the common-used language list.
I think the code should be fine, now it can be merged.

**Comment by Fevol** [comment]
Ah, I completely missed that in the documentation too. 😅
I'll merge the PR now, and try to come up with some code to check whether the user has the advanced tier enabled or just the standard tier. 
Thank you again for all the help and testing, I really, really appreciate it!

**Pull request merged**
